[build]
  base = "belajar-pintar"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://belajar-pintar-api.onrender.com"
